SELECT PRODUCT.PRODUCT_CODE AS PRODUCT_CODE, PRODUCT.PRICE * SUM(SALE.SALES_AMOUNT) AS SALES
FROM PRODUCT JOIN OFFLINE_SALE AS SALE ON PRODUCT.PRODUCT_ID = SALE.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC