SELECT COUNT(INFO.FISH_TYPE) AS FISH_COUNT, NAME.FISH_NAME
FROM FISH_INFO AS INFO JOIN FISH_NAME_INFO AS NAME ON INFO.FISH_TYPE = NAME.FISH_TYPE
GROUP BY INFO.FISH_TYPE, NAME.FISH_NAME
ORDER BY FISH_COUNT DESC;