SELECT SUM(FISH) AS FISH_COUNT
FROM (
    SELECT COUNT(FISH_INFO.FISH_TYPE) AS FISH
    FROM FISH_INFO LEFT JOIN FISH_NAME_INFO AS NAME ON FISH_INFO.FISH_TYPE = NAME.FISH_TYPE
    WHERE NAME.FISH_NAME = "BASS" OR NAME.FISH_NAME = "SNAPPER"
    GROUP BY FISH_INFO.FISH_TYPE
) AS SUB
