SELECT INFO.ID AS ID, 
       NAME.FISH_NAME AS FISH_NAME, 
       INFO.LENGTH AS LENGTH
FROM FISH_INFO AS INFO 
LEFT JOIN FISH_NAME_INFO AS NAME ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE INFO.LENGTH = (
    SELECT MAX(SUB.LENGTH)
    FROM FISH_INFO AS SUB
    WHERE SUB.FISH_TYPE = INFO.FISH_TYPE
);