SELECT SUM(GRADE.SCORE) AS SCORE, GRADE.EMP_NO, EMPLOYEES.EMP_NAME, EMPLOYEES.POSITION, EMPLOYEES.EMAIL
FROM HR_GRADE AS GRADE 
LEFT JOIN HR_EMPLOYEES AS EMPLOYEES ON GRADE.EMP_NO = EMPLOYEES.EMP_NO 
GROUP BY GRADE.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
