SELECT BOARD.TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE 
FROM USED_GOODS_BOARD as BOARD join USED_GOODS_REPLY as REPLY on BOARD.BOARD_ID = REPlY.BOARD_ID 
WHERE YEAR(BOARD.CREATED_DATE) = 2022 AND MONTH(BOARD.CREATED_DATE) = 10 ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC